config/routes.rb
PbGallery::Application.routes.draw do
  
  get "gallery_permission/new"
  post "gallery_permission/create"
  get "welcome/index"
  root 'welcome#index'
  
  
  resources :issues

  devise_for :users, path: '', controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', registration: 'register'}
  
  resources :users
  get 'profile' => 'users#profile'

  resources :galleries do
    resources :images
  end
  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :user
  
  def solved?
    self.status == 'solved'
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order(status: :asc).order(date: :desc)
  end

  # GET /issues/new
  def new
    @issues = Issue.all
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
    @issues = Issue.all
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.user = current_user
    @issue.date = Time.now

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issues_path, notice: t('issue.created') }
        format.json { render action: 'index' }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    @issue.assign_attributes(issue_params)
    @issue.user = current_user
    @issue.date = Time.now
    respond_to do |format|
      if @issue.save
        format.html { redirect_to issues_path, notice:  t('issue.updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name, :text, :status)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def row_class(issue)
    if issue.solved?
      :success
    else
      ''
    end
  end
end

app/views/issues/_form.html.haml
.col-md-6
  = form_for @issue do |f|
    - if @issue.errors.any?
      #error_explanation
        %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
        %ul
          - @issue.errors.full_messages.each do |msg|
            %li= msg
  
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :text
      = f.text_area :text, class: 'form-control', rows: 6
    .form-group
      = link_to t('links.cancel'), issues_path, class: 'btn btn-default'
      = f.submit t('links.save'), class: 'btn btn-primary'

app/views/issues/_table.html.haml
%table.table.table-bordered.table-condensed.table-hover
  %tr
    %th= t('issue.name')
    %th= t('issue.text')
    %th= t('issue.date')
    %th= t('issue.user')
    %th= t('issue.status')
    %th
   
  - @issues.each do |issue|
    
    %tr{class: row_class(issue)}
      %td= issue.name
      %td= issue.text
      %td
        .no-wrap= l(issue.date)
      %td= issue.user.first_name
      %td
        - if issue.solved?
          %span.label.label-success= issue.status
        - else
          %span.label.label-default= issue.status
      %td
        .btn-group<
          =link_to t('links.edit'), edit_issue_path(issue), class: 'btn btn-sm btn-primary' unless issue.solved?
          =link_to t('links.issue.set_solved'), issue_path(:id => issue.id, :issue => {:status => :solved }), {:method => :patch, class: 'btn btn-sm btn-success'} unless issue.solved?
          =link_to t('links.delete'), issue, :method => :delete, :data => { :confirm => t('links.confirmation') }, class: 'btn btn-sm btn-danger'
            

app/views/issues/edit.html.haml
%h1= t('issue.edit_issue')
.issues-form
  = render 'form'
.issues-table
  = render :partial => 'table'

app/views/issues/index.html.haml
%h1= t('issue.title')

.row
  .col-md-10
    %h5= t('issue.description')
  .col-md-2
    = link_to t('issue.new_issue'), new_issue_path, class: 'btn btn-primary'
  
.issues-table
  = render :partial => 'table'

app/views/issues/new.html.haml
%h1= t('issue.new_issue')
.issues-form
  = render 'form'
.issues-table
  = render :partial => 'table'