config/routes.rb
PbGallery::Application.routes.draw do
  
  get "gallery_permission/new"
  post "gallery_permission/create"
  get "welcome/index"
  root 'welcome#index'
  
  
  resources :issues

  devise_for :users, path: '', controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', registration: 'register'}
  
  resources :users
  get 'profile' => 'users#profile'

  resources :galleries do
    resources :images
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :role
  
  has_and_belongs_to_many :permitted_galleries, class_name: Gallery, join_table: :gallery_permissions
  has_many :galleries, foreign_key: :owner_id
  
  after_initialize :init_role
  def init_role
    self.role ||= Role.find_by(name: :watcher)
    self.approved = true                        #TODO: do not require approval, make to general setting in app?
  end
  
  validates :first_name, presence: true
  validates :name, presence: true
  
  after_create :send_waiting_for_approval_mail
  def send_waiting_for_approval_mail
    #TODO: activate and test!!
    #AdminMailer.new_user_waiting_for_approval(self).deliver
  end
  
  def full_name
    "#{self.first_name} #{self.name}"
  end
  def to_s
    "#{self.full_name} <#{self.email}>"
  end
  
  def admin?
    return self.role? 'admin'
  end
  
  def role?(role)
    if self.role
      self.role.name.to_s.downcase == role
    else
      false
    end
  end
  
  # override for approval functionality
  def active_for_authentication? 
    super && approved? 
  end 

  # override for approval functionality
  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @q = User.search(params[:q])
    @users = @q.result(distinct: true).paginate(page: params[:page], per_page: 30).order(email: :asc).includes(:role)
  end

  # GET /profile
  def profile
    @user = current_user    
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.approved = true

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: t('user.created') }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: t('user.updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :name, :email, :role_id, :approved)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_row_class(user)
    if user.admin?
      'info'
    elsif not user.approved?
      'danger'
    end 
  end
end

app/views/users/_form.html.haml
.user-form.col-md-3
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg
  
    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: 'form-control'
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :email
      = f.text_field :email, class: 'form-control'
    .form-group
      = f.label :role
      = f.collection_select :role_id, Role.all, :id, :name, {default: :watcher}, {class: 'form-control'}
    .form-group
      = link_to t('links.cancel'), users_path, class: 'btn btn-default'
      = f.submit t('links.save'), class: 'btn btn-primary'
      

app/views/users/_table.html.haml
.user-table
  %table.table.table-bordered.table-condensed.table-hover
    %tr
      %th= t('user.first_name')
      %th= t('user.name')
      %th= t('user.email')
      %th= t('user.role')
      %th
    %tr.search-row
      = search_form_for @q, class: 'form-inline' do |f|
        %th= f.text_field :first_name_cont, placeholder: t('user.first_name'), class: 'form-control search-input'
        %th= f.text_field :name_cont, placeholder: t('user.name'), class: 'form-control search-input'
        %th= f.text_field :email_cont, placeholder: t('user.email'), class: 'form-control search-input'
        %th
        %th
          %span.btn-group<
            = f.submit t('links.search.filter'), {'data-no-turbolink' => '', class: "btn btn-success"}
            = link_to t('links.search.clear_filter'), users_path, {'data-no-turbolink' => '', class: "btn btn-default"}
      

  
    - @users.each do |user|
      %tr{class: user_row_class(user)}
        %td= user.first_name
        %td= user.name
        %td= user.email
        %td= user.role.translated_name
        %td
          .btn-group<
            = link_to t('links.user.profile'), user_path(user), class: 'btn btn-sm btn-default'
            = link_to t('links.edit'), edit_user_path(user), class: 'btn btn-sm btn-primary'
            = link_to t('links.user.set_approved'), user_path(:id => user.id, :user => {:approved => 'true' }), {:method => :patch, class: 'btn btn-sm btn-success'} unless user.approved?
            = link_to t('links.delete'), user, :method => :delete, :data => { :confirm => t('links.confirmation') }, class: 'btn btn-sm btn-danger'

  = will_paginate @users, renderer: BootstrapPagination::Rails

app/views/users/edit.html.haml
%h1= t('user.edit_user')

= render 'form'

app/views/users/index.html.haml
%h1= t('user.title')


.row
  .col-md-10
    %h5= t('user.description')
  .col-md-2
    = link_to t('user.invite_user'), new_user_invitation_path, class: 'btn btn-primary'
    
.users-table
  = render :partial => 'table'

app/views/users/new.html.haml
%h1= t('user.new_user')

= render 'form'

app/views/users/profile.html.haml
%h1= t('user.profile')
%p
  %b= t('user.first_name')
  = @user.first_name
%p
  %b= t('user.name')
  = @user.name
%p
  %b= t('user.email')
  = @user.email
%p
  %b= t('user.role')
  = @user.role.name

%h3= t('links.edit_account')
= link_to t('links.edit_account'), edit_user_registration_path, class: 'btn btn-success'
  
%h3= t('devise.cancel_account')
= button_to t('devise.cancel_account'), registration_path(resource_name), :data => { :confirm => t('links.confirmation') }, :method => :delete, class: 'btn btn-danger'
 

app/views/users/show.html.haml
%h1= t('user.profile')
%p
  %b First name:
  = @user.first_name
%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Role:
  = @user.role.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path