config/routes.rb
PbGallery::Application.routes.draw do
  
  get "gallery_permission/new"
  post "gallery_permission/create"
  get "welcome/index"
  root 'welcome#index'
  
  
  resources :issues

  devise_for :users, path: '', controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', registration: 'register'}
  
  resources :users
  get 'profile' => 'users#profile'

  resources :galleries do
    resources :images
  end
  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_and_belongs_to_many :permitted_users, class_name: User, join_table: :gallery_permissions
  belongs_to :owner, class_name: User
  validates_uniqueness_of :key
  validates_presence_of :name, :date
  
  TYPES =
    [ [I18n.t('gallery.self_hosted'), 'SelfHostedGallery'], [I18n.t('gallery.picasa'), 'PicasaGallery'] ]
  
  
  def permitted_for?(user)
    permitted_users.include? user
  end
end

app/models/gallery/amazon_s3_gallery.rb
class AmazonS3Gallery < Gallery
  

end

app/models/gallery/picasa_gallery.rb
class PicasaGallery < Gallery
  
  
  def images
    repository = PicasaWebAlbums.get_repository(ENV['PICASA_GOOGLE_USER'], ENV['PICASA_GOOGLE_PASSWORD'])
    picasa_images = repository.get_photos_by_album_id(self.picasa_webalbum_id)
  end
  
  def number_of_images
    return 0
  end

end

app/models/gallery/self_hosted_gallery.rb
class SelfHostedGallery < Gallery
  has_many :images, foreign_key: :gallery_id

  def number_of_images
    images.count
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    if admin?
      # load all galleries for manage overview
      @q = Gallery.search(params[:q])
      @galleries = @q.result(distinct: true).paginate(page: params[:page], per_page: 10).order(date: :desc)
      @owners = User.includes(:role).where('roles.name' => 'admin')
      render 'manage'
    else
      # allow user only to see permitted galleries
      @galleries = current_user.permitted_galleries
    end
  end
  
  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
    case params[:tab]
    when 'images'
      case @gallery.type
      when 'PicasaGallery'
        repo = PicasaWebAlbums.get_repository(ENV['PICASA_GOOGLE_USER'], ENV['PICASA_GOOGLE_PASSWORD'])
        @albums = repo.get_all_albums
        render 'edit_picasa'
      when 'SelfHostedGallery'
        @image = Image.new
        render 'edit_images'
      end
    when 'permissions'
      render 'edit_permissions'
    when 'preview'
      render 'preview'
    when 'general'
      render 'edit' #this action
    else
      redirect_to edit_gallery_path(@gallery, tab: 'general')
    end
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.owner = current_user

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to edit_gallery_path(@gallery, tab: :images), notice: t('gallery.created') }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to edit_gallery_path(@gallery), notice: t('gallery.updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :date, :photographer, :key, :type, :published, :picasa_webalbum_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper

  def active_tab_class(tab)
    if params[:tab] == tab
      return 'active'
    else
      return "#{params[:tab]} - #{tab}"
    end
  end
end

app/views/galleries/_edit_tabs.html.haml
%h1
  = t('gallery.edit')
  = "'#{@gallery.name}'"

    
         
.tabs
  %ul.nav.nav-tabs
    %li{class: active_tab_class('general')}= link_to t('gallery.manage.general'), "?tab=general"
    - if @gallery.is_a? SelfHostedGallery
      %li{class: active_tab_class('images')}= link_to t('gallery.manage.images'), "?tab=images"
    - elsif @gallery.is_a? PicasaGallery
      %li{class: active_tab_class('images')}= link_to t('gallery.manage.picasa'), "?tab=images"
    %li{class: active_tab_class('permissions')}= link_to t('gallery.manage.permissions'), "?tab=permissions"
    %li{class: active_tab_class('preview')}= link_to t('gallery.manage.preview'), "?tab=preview"
    - if @gallery.published?
      %li= link_to t('links.gallery.set_unpublished'), gallery_path(:id => @gallery.id, :gallery => {:published => :false }), {:method => :patch, class: 'btn btn-sm btn-warning'}
    - else
      %li= link_to t('links.gallery.set_published'), gallery_path(:id => @gallery.id, :gallery => {:published => :true }), {:method => :patch, class: 'btn btn-sm btn-success'}
 

app/views/galleries/_form.html.haml
.gallery-form.col-md-3
  = form_for @gallery.becomes(Gallery), html: { class: "form form-inline" } do |f|
    .form-group
      = f.label :type
      = f.select :type, Gallery::TYPES, {}, {class: 'form-control'}
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :date
      = f.date_field :date, class: 'form-control'
    .form-group
      = f.label :photographer
      = f.text_field :photographer, class: 'form-control'
    .form-group
      = f.label :key
      = f.text_field :key, class: 'form-control'
    .form-group
      = link_to t('links.cancel'), galleries_path, class: 'btn btn-default'
      = f.submit t('links.save'), class: 'btn btn-primary'

app/views/galleries/_show.html.haml
.gallery.col-md-10.col-md-offset-1
  - if @gallery.is_a? SelfHostedGallery
    = render_gallery_for @gallery.images, title: 'name'
  - elsif @gallery.is_a? PicasaGallery
    = render_gallery_for @gallery.images, title: 'file_name', thumbnail: :url, original: :url 

app/views/galleries/_table.html.haml
.galleries-table
  %table.table.table-bordered.table-condensed.table-hover
    %tr
      %th= t('gallery.name')
      %th= t('gallery.date')
      %th= t('gallery.owner')
      %th= t('gallery.type')
      %th= t('gallery.published')
      %th= t('gallery.images')
      %th= t('gallery.permitted_users')
      %th
    %tr.search-row
      = search_form_for @q, class: 'form-inline' do |f|
        %th= f.text_field :name_cont, placeholder: t('gallery.name'), class: 'form-control search-input'
        %th= f.text_field :date_cont, placeholder: t('gallery.date'), class: 'form-control search-input'
        %th= f.collection_select :owner_id_eq, @owners, :id, :full_name , {include_blank: t('search.all')}, {class: 'form-control search-input'}
        %th= f.select :type_eq, (Gallery::TYPES), {}, {class: 'form-control search-input'}
        %th
        %th
        %th
        %th
          %span.btn-group<
            = f.submit t('links.search.filter'), {'data-no-turbolink' => '', class: "btn btn-success"}
            = link_to t('links.search.clear_filter'), galleries_path, {'data-no-turbolink' => '' ,class: "btn btn-default"}
  
  
    - @galleries.each do |gallery|
      %tr
        %td= gallery.name
        %td= l(gallery.date)
        %td= gallery.owner.full_name if gallery.owner
        %td
          %span.badge= gallery.type
        %td
          %span.badge= t('gallery.published') if gallery.published?
        %td
          %span.badge= gallery.number_of_images
        %td
          %span.badge= gallery.permitted_users.count 
        %td
          .btn-group< 
            = link_to t('links.show'), gallery_path(gallery), class: 'btn btn-sm btn-default'
            = link_to t('links.edit'), edit_gallery_path(gallery), class: 'btn btn-sm btn-primary'
            = link_to t('links.delete'), gallery_path(gallery), :method => :delete, :data => { :confirm => t('links.confirmation') }, class: 'btn btn-sm btn-danger'
  
  = will_paginate @galleries, renderer: BootstrapPagination::Rails

app/views/galleries/edit.html.haml
= render partial: "edit_tabs"

= render 'form'

app/views/galleries/edit_images.html.haml
= render partial: "edit_tabs"

= form_for [@gallery.becomes(Gallery), @image], :html => { :multipart => true, :id => "fileupload"  } do |f|
  .row.fileupload-buttonbar
    .col-md-8
      %span.btn.btn-success.fileinput-button
        %i.glyphicon.glyphicon-plus
        %span Add files...
        = f.file_field :file, multiple: true, name: 'image[file]', accept: "image/jpeg"
      %button.btn.btn-primary.start{:type => "submit"}
        %i.glyphicon.glyphicon-upload
        %span Start upload
      %button.btn.btn-warning.cancel{:type => "reset"}
        %i.glyphicon.glyphicon-ban-circle
        %span Cancel upload
      %button.btn.btn-danger.delete{:type => "button"}
        %i.glyphicon.glyphicon-trash
        %span Delete
      %input.toggle{:type => "checkbox"}
      %span.fileupload-process
      
    .col-md-4.fade.fileupload-progress
      .progress.progress-striped.active
        .progress-bar.progress-bar-success{:role => "progressbar",:style => "width:0%;"}
          %span.sr-only
      .progress-extended &nbsp;
      
  %table.table.table-striped
    %tbody.files


%script#template-upload{:type => "text/x-tmpl"}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-upload.fade
    %td.preview
      %span.preview.fade
    %td.name
      %span
        {%=file.name%}
    %td.size
      %span
        {%=o.formatFileSize(file.size)%}
        
    {% if (file.error) { %}
    %td.error{colspan: 2}
      %span.label.label-important {%=locale.fileupload.error%}
      {%=locale.fileupload.errors[file.error] || file.error%}
    {% } else if (o.files.valid && !i) { %}
    %td
      .progress.progress-success.progress-striped.active
        .progress-bar.progress-bar-success{style: "width:0%;"}
    
    %td.start 
      %button.btn.btn-primary
        %i.glyphicon.glyphicon-upload
        %span {%=locale.fileupload.start%}
    {% } %}
    {% if (!i) { %}
    %td.cancel
      %button.btn.btn-warning
        %i.glyphicon.glyphicon-ban-circle
        %span {%=locale.fileupload.cancel%}
      {% } %}
    {% } %}
  

%script#template-download{:type => "text/x-tmpl"}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-download.fade
    {% if (file.error) { %}
    %td
    %td.name
      %span {%=file.name%}
    %td.error{colspan: 2}
      %span.label.label-important {%=locale.fileupload.error%}
      {%=locale.fileupload.errors[file.error] || file.error%}
    {% } else { %}
    %td.preview 
      {% if (file.thumbnail_url) { %}
      %img{src: "{%=file.thumbnail_url%}"}
      {% } %}
    %td.name {%=file.name%}
    %td.size 
      %span {%=o.formatFileSize(file.size)%}
    %td{colspan: 2}
    {% } %}
    %td.delete
      %button.btn.btn-danger{'data-type' => "{%=file.delete_type%}", 'data-url' => "{%=file.delete_url%}"}
        %i.glyphicon.glyphicon-trash
        %span {%=locale.fileupload.destroy%}
      %input{type: "checkbox", name: "delete", value: '1'}
  {% } %}


%script{:charset => "utf-8", :type => "text/javascript"}
  $(function () {
  
  $('#fileupload').fileupload({
  dataType: 'json'
  });

  $.getJSON($('#fileupload').prop('action'), function (files) {
  var fu = $('#fileupload').data('blueimpFileupload'), template;
  
  template = fu._renderDownload(files).appendTo($('#fileupload .files'));

  fu._reflow = fu._transition && template.length && template[0].offsetWidth;
  template.addClass('in');
  $('#loading').remove();
  });
  });

app/views/galleries/edit_permissions.html.haml
= render partial: "edit_tabs"

.galleries-table
  %table.table.table-bordered.table-condensed.table-hover
    %tr
      %th= t('user.full_name')
      %th= t('user.email')
      %th
  
    - @gallery.permitted_users.each do |user|
      %tr
        %td= user.full_name
        %td= user.email
        %td
          .btn-group< 
            %p Currently no actions available

app/views/galleries/edit_picasa.html.haml
= render partial: "edit_tabs"

.gallery-form.col-md-3
  = form_for @gallery.becomes(Gallery) do |f|
    - if @gallery.errors.any?
      #error_explanation
        %h2= "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:"
        %ul
          - @gallery.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.label :picasa_webalbum_id
      = f.collection_select :picasa_webalbum_id, @albums, :id, :title, {}, {class: 'form-control'}
    .form-group
      = link_to t('links.cancel'), galleries_path, class: 'btn btn-default'
      = f.submit t('links.save'), class: 'btn btn-primary'

app/views/galleries/index.html.haml
%h1= t('gallery.title')
%h5= t('gallery.index.description')

.gallery-table
  %table.table.table-bordered.table-condensed.table-hover
    %tr
      %th= t('gallery.name')
      %th= t('gallery.date')
      %th= t('gallery.owner')
      %th= t('gallery.images')
  
    - @galleries.each do |gallery|
      %tr
        %td= link_to gallery.name, gallery_path(gallery)
        %td= l(gallery.date)
        %td= gallery.owner.full_name if gallery.owner
        %td
          %span.badge= gallery.images.count 

app/views/galleries/manage.html.haml
%h1= t('gallery.title')
.row
  .col-md-10
    %h5= t('gallery.manage.description')
  .col-md-2  
    = link_to t('gallery.new_gallery'), new_gallery_path, class: 'btn btn-primary'

.gallery-table
  = render :partial => 'table'

app/views/galleries/new.html.haml
%h1= t('gallery.new_gallery')
.gallery-form
  = render 'form'

app/views/galleries/preview.html.haml
= render partial: "edit_tabs"
.gallery-preview
  =render partial: 'show'    

app/views/galleries/show.html.haml
%h3= @gallery.name
%h4= l(@gallery.date)
%h4= @gallery.photographer

= render partial: 'show'
    