config/routes.rb
PbGallery::Application.routes.draw do
  
  get "gallery_permission/new"
  post "gallery_permission/create"
  get "welcome/index"
  root 'welcome#index'
  
  
  resources :issues

  devise_for :users, path: '', controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', registration: 'register'}
  
  resources :users
  get 'profile' => 'users#profile'

  resources :galleries do
    resources :images
  end
  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t('site.title')
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-static-top.navbar-inverse.navbar-collapse{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: "button", 'data-toggle' => "collapse", 'data-target' => "#navbar-main"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to t('site.title'), root_path, html_options = {class: "navbar-brand"}

        .collapse.navbar-collapse#navbar-main
          %ul.nav.navbar-nav
            - if admin?
              = bootstrap_pill_link_to t('site.dashboard.title'), root_path
              = bootstrap_pill_link_to t('user.title'), users_path
              = bootstrap_pill_link_to t('gallery.title'), galleries_path
              = bootstrap_pill_link_to t('issue.title'), issues_path
            - elsif current_user
              = bootstrap_pill_link_to t('gallery.title'), galleries_path
              = bootstrap_pill_link_to t('gallery_permission.new'), gallery_permission_new_path
            
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              - if admin?
                %li= link_to "#{current_user.email} (#{current_user.role.translated_name})", profile_path
              - else
                %li= link_to "#{current_user.email}", profile_path
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
              
    .container
      .row
        - flash.each do |name, msg|
          %div{class: "alert alert-dismissable #{bootstrap_class_for(name)}"}
            = msg
            %button.close{:type => :type, 'data-dismiss' => "alert", 'aria-hidden' => 'true'} &times;

      .row
        =yield

     
     
    .navbar.navbar-static-bottom.footer
      .footer-content
        %p.copyright.pull-right
          &copy; 
          = Time.now.year
          Tim auf der Landwehr - 
          %a{href: "http://taufderl.de"} taufderl.de
          